package edu.courseflow.promotion.service;

public final class PromotionErrorCodes {

    public static final String ADMIN_OPERATION_RATE_LIMITED = "ADMIN_OPERATION_RATE_LIMITED";

    public static final String COUPON_IMPORT_MANAGE_FORBIDDEN = "COUPON_IMPORT_MANAGE_FORBIDDEN";
    public static final String COUPON_IMPORT_READ_FORBIDDEN = "COUPON_IMPORT_READ_FORBIDDEN";
    public static final String COUPON_IMPORT_REVIEW_FORBIDDEN = "COUPON_IMPORT_REVIEW_FORBIDDEN";
    public static final String COUPON_IMPORT_OPERATOR_REQUIRED = "COUPON_IMPORT_OPERATOR_REQUIRED";
    public static final String COUPON_IMPORT_SELF_APPROVAL_BLOCKED = "COUPON_IMPORT_SELF_APPROVAL_BLOCKED";
    public static final String COUPON_IMPORT_SELF_COMMIT_BLOCKED = "COUPON_IMPORT_SELF_COMMIT_BLOCKED";

    public static final String COUPON_IMPORT_DRY_RUN_NOT_FOUND = "COUPON_IMPORT_DRY_RUN_NOT_FOUND";
    public static final String COUPON_IMPORT_APPROVAL_NOT_FOUND = "COUPON_IMPORT_APPROVAL_NOT_FOUND";
    public static final String COUPON_IMPORT_DRY_RUN_NOT_COMMIT_READY = "COUPON_IMPORT_DRY_RUN_NOT_COMMIT_READY";
    public static final String COUPON_IMPORT_DRY_RUN_EXPIRED = "COUPON_IMPORT_DRY_RUN_EXPIRED";
    public static final String COUPON_IMPORT_ALREADY_COMMITTED = "COUPON_IMPORT_ALREADY_COMMITTED";
    public static final String COUPON_IMPORT_RESULT_HASH_MISMATCH = "COUPON_IMPORT_RESULT_HASH_MISMATCH";
    public static final String COUPON_IMPORT_PAYLOAD_CHANGED = "COUPON_IMPORT_PAYLOAD_CHANGED";
    public static final String COUPON_IMPORT_DUPLICATE_CODE = "COUPON_IMPORT_DUPLICATE_CODE";

    public static final String COUPON_IMPORT_APPROVAL_ALREADY_EXISTS = "COUPON_IMPORT_APPROVAL_ALREADY_EXISTS";
    public static final String COUPON_IMPORT_APPROVAL_NOT_PENDING = "COUPON_IMPORT_APPROVAL_NOT_PENDING";
    public static final String COUPON_IMPORT_APPROVAL_NOT_APPROVED = "COUPON_IMPORT_APPROVAL_NOT_APPROVED";
    public static final String COUPON_IMPORT_APPROVAL_EXPIRED = "COUPON_IMPORT_APPROVAL_EXPIRED";
    public static final String COUPON_IMPORT_APPROVAL_SUBJECT_CHANGED = "COUPON_IMPORT_APPROVAL_SUBJECT_CHANGED";

    public static final String REDEMPTION_REVERSAL_OPERATOR_REQUIRED = "REDEMPTION_REVERSAL_OPERATOR_REQUIRED";
    public static final String REDEMPTION_REVERSAL_APPROVAL_REQUIRED = "REDEMPTION_REVERSAL_APPROVAL_REQUIRED";
    public static final String REDEMPTION_REVERSAL_APPROVAL_NOT_FOUND = "REDEMPTION_REVERSAL_APPROVAL_NOT_FOUND";
    public static final String REDEMPTION_REVERSAL_APPROVAL_ALREADY_EXISTS =
            "REDEMPTION_REVERSAL_APPROVAL_ALREADY_EXISTS";
    public static final String REDEMPTION_REVERSAL_APPROVAL_NOT_PENDING =
            "REDEMPTION_REVERSAL_APPROVAL_NOT_PENDING";
    public static final String REDEMPTION_REVERSAL_APPROVAL_NOT_APPROVED =
            "REDEMPTION_REVERSAL_APPROVAL_NOT_APPROVED";
    public static final String REDEMPTION_REVERSAL_APPROVAL_EXPIRED = "REDEMPTION_REVERSAL_APPROVAL_EXPIRED";
    public static final String REDEMPTION_REVERSAL_APPROVAL_SUBJECT_CHANGED =
            "REDEMPTION_REVERSAL_APPROVAL_SUBJECT_CHANGED";
    public static final String REDEMPTION_REVERSAL_APPROVAL_PAYLOAD_CHANGED =
            "REDEMPTION_REVERSAL_APPROVAL_PAYLOAD_CHANGED";
    public static final String REDEMPTION_REVERSAL_SELF_APPROVAL_BLOCKED =
            "REDEMPTION_REVERSAL_SELF_APPROVAL_BLOCKED";
    public static final String REDEMPTION_REVERSAL_SELF_EXECUTION_BLOCKED =
            "REDEMPTION_REVERSAL_SELF_EXECUTION_BLOCKED";

    public static final String IDEMPOTENCY_KEY_REUSED = "IDEMPOTENCY_KEY_REUSED";
    public static final String IDEMPOTENCY_KEY_EXPIRED = "IDEMPOTENCY_KEY_EXPIRED";
    public static final String IDEMPOTENCY_KEY_NOT_REPLAYABLE = "IDEMPOTENCY_KEY_NOT_REPLAYABLE";
    public static final String IDEMPOTENCY_KEY_ACQUIRE_FAILED = "IDEMPOTENCY_KEY_ACQUIRE_FAILED";

    public static final String RETENTION_OPERATOR_REQUIRED = "RETENTION_OPERATOR_REQUIRED";
    public static final String RETENTION_ADMIN_FORBIDDEN = "RETENTION_ADMIN_FORBIDDEN";
    public static final String RETENTION_REVIEW_FORBIDDEN = "RETENTION_REVIEW_FORBIDDEN";
    public static final String RETENTION_PLATFORM_ADMIN_REQUIRED = "RETENTION_PLATFORM_ADMIN_REQUIRED";
    public static final String RETENTION_EXECUTION_DISABLED = "RETENTION_EXECUTION_DISABLED";
    public static final String RETENTION_RESTORE_DRILL_ALREADY_EXISTS = "RETENTION_RESTORE_DRILL_ALREADY_EXISTS";
    public static final String RETENTION_RESTORE_DRILL_INVALID = "RETENTION_RESTORE_DRILL_INVALID";
    public static final String RETENTION_APPROVAL_NOT_FOUND = "RETENTION_APPROVAL_NOT_FOUND";
    public static final String RETENTION_APPROVAL_ALREADY_EXISTS = "RETENTION_APPROVAL_ALREADY_EXISTS";
    public static final String RETENTION_APPROVAL_NOT_PENDING = "RETENTION_APPROVAL_NOT_PENDING";
    public static final String RETENTION_APPROVAL_NOT_APPROVED = "RETENTION_APPROVAL_NOT_APPROVED";
    public static final String RETENTION_APPROVAL_EXPIRED = "RETENTION_APPROVAL_EXPIRED";
    public static final String RETENTION_APPROVAL_CONSUMED = "RETENTION_APPROVAL_CONSUMED";
    public static final String RETENTION_APPROVAL_NOT_REPLAYABLE = "RETENTION_APPROVAL_NOT_REPLAYABLE";
    public static final String RETENTION_SELF_APPROVAL_BLOCKED = "RETENTION_SELF_APPROVAL_BLOCKED";
    public static final String RETENTION_SELF_EXECUTION_BLOCKED = "RETENTION_SELF_EXECUTION_BLOCKED";
    public static final String RETENTION_DRY_RUN_STALE = "RETENTION_DRY_RUN_STALE";
    public static final String RETENTION_RESULT_HASH_MISMATCH = "RETENTION_RESULT_HASH_MISMATCH";
    public static final String RETENTION_EXECUTION_IDEMPOTENCY_REUSED = "RETENTION_EXECUTION_IDEMPOTENCY_REUSED";
    public static final String RETENTION_EXECUTION_IDEMPOTENCY_IN_PROGRESS = "RETENTION_EXECUTION_IDEMPOTENCY_IN_PROGRESS";
    public static final String RETENTION_EXECUTION_IDEMPOTENCY_NOT_REPLAYABLE = "RETENTION_EXECUTION_IDEMPOTENCY_NOT_REPLAYABLE";
    public static final String RETENTION_EXECUTION_ACQUIRE_FAILED = "RETENTION_EXECUTION_ACQUIRE_FAILED";
    public static final String RETENTION_EXECUTION_NOT_STARTED = "RETENTION_EXECUTION_NOT_STARTED";
    public static final String RETENTION_EXECUTION_NOT_IN_PROGRESS = "RETENTION_EXECUTION_NOT_IN_PROGRESS";
    public static final String RETENTION_EXECUTION_RESPONSE_NOT_REPLAYABLE = "RETENTION_EXECUTION_RESPONSE_NOT_REPLAYABLE";

    private PromotionErrorCodes() {
    }
}
