CREATE DATABASE cf_identity;
CREATE DATABASE cf_keycloak;
CREATE DATABASE cf_access_control;
CREATE DATABASE cf_user_management;
CREATE DATABASE cf_organization;
CREATE DATABASE cf_course;
CREATE DATABASE cf_enrollment;
CREATE DATABASE cf_assignment;
CREATE DATABASE cf_deadline;
CREATE DATABASE cf_announcement;
CREATE DATABASE cf_discussion;
CREATE DATABASE cf_notification;
CREATE DATABASE cf_media;
CREATE DATABASE cf_analytics;
CREATE DATABASE cf_gradebook;
CREATE DATABASE cf_quiz;
CREATE DATABASE cf_certificate;
CREATE DATABASE cf_peer_review;
CREATE DATABASE cf_live_session;
CREATE DATABASE cf_review;
CREATE DATABASE cf_outbox;

ALTER DATABASE cf_identity OWNER TO courseflow;
ALTER DATABASE cf_keycloak OWNER TO courseflow;
ALTER DATABASE cf_access_control OWNER TO courseflow;
ALTER DATABASE cf_user_management OWNER TO courseflow;
ALTER DATABASE cf_organization OWNER TO courseflow;
ALTER DATABASE cf_course OWNER TO courseflow;
ALTER DATABASE cf_enrollment OWNER TO courseflow;
ALTER DATABASE cf_assignment OWNER TO courseflow;
ALTER DATABASE cf_deadline OWNER TO courseflow;
ALTER DATABASE cf_announcement OWNER TO courseflow;
ALTER DATABASE cf_discussion OWNER TO courseflow;
ALTER DATABASE cf_notification OWNER TO courseflow;
ALTER DATABASE cf_media OWNER TO courseflow;
ALTER DATABASE cf_analytics OWNER TO courseflow;
ALTER DATABASE cf_gradebook OWNER TO courseflow;
ALTER DATABASE cf_quiz OWNER TO courseflow;
ALTER DATABASE cf_certificate OWNER TO courseflow;
ALTER DATABASE cf_peer_review OWNER TO courseflow;
ALTER DATABASE cf_live_session OWNER TO courseflow;
ALTER DATABASE cf_review OWNER TO courseflow;
ALTER DATABASE cf_outbox OWNER TO courseflow;
