from __future__ import annotations

from pathlib import Path

from enterprise_dp.contracts import ValidationResult


REQUIRED_DIRECTORIES = (
    "contracts",
    "contracts/data-products",
    "contracts/events",
    "contracts/policies",
    "contracts/topics",
    "products",
    "products/enterprise-commerce",
    "products/lms-courseflow",
    "products/lms-courseflow/domains",
    "products/lms-courseflow/domains/assessment",
    "products/lms-courseflow/domains/commerce",
    "products/lms-courseflow/domains/learning",
    "products/lms-courseflow/domains/recommendation",
    "products/lms-courseflow/use-cases",
    "domains",
    "domains/compliance",
    "domains/customer",
    "domains/enterprise-reporting",
    "domains/finance",
    "domains/ml-ai",
    "domains/product-analytics",
    "domains/recommendation",
    "domains/risk-compliance",
    "domains/workforce",
    "catalog",
    "governance",
    "templates",
    "use-cases",
    "platform",
    "platform/ingestion",
    "platform/lakehouse",
    "platform/processing",
    "platform/orchestration",
    "platform/quality",
    "platform/governance",
    "platform/lineage",
    "platform/serving",
    "platform/observability",
    "platform/security",
    "platform/developer-experience",
    "platform/environments/local",
    "platform/environments/staging",
    "platform/environments/prod",
    "platform/runtime",
    "platform/runtime/local",
    "platform/runtime/iac",
    "platform/runtime/iac/staging",
    "platform/runtime/iac/prod",
    "platform/runtime/evidence",
    "docs/architecture",
    "docs/adr",
    "docs/team",
    "src/enterprise_dp",
    "tests",
)


REQUIRED_FILES = (
    "README.md",
    "Makefile",
    "pyproject.toml",
    "contracts/README.md",
    "contracts/event-envelope.v1.schema.json",
    "contracts/policies/README.md",
    "contracts/policies/access-policies.yaml",
    "contracts/policies/access-personas.yaml",
    "contracts/policies/consumer-contracts.yaml",
    "contracts/policies/retention-policies.yaml",
    "products/README.md",
    "products/enterprise-commerce/onboarding.yaml",
    "products/lms-courseflow/README.md",
    "products/lms-courseflow/onboarding.yaml",
    "products/lms-courseflow/domains/README.md",
    "products/lms-courseflow/domains/assessment/README.md",
    "products/lms-courseflow/domains/commerce/README.md",
    "products/lms-courseflow/domains/learning/README.md",
    "products/lms-courseflow/domains/recommendation/README.md",
    "products/lms-courseflow/use-cases/README.md",
    "domains/README.md",
    "domains/registry.yaml",
    "domains/compliance/README.md",
    "domains/customer/README.md",
    "domains/enterprise-reporting/README.md",
    "domains/finance/README.md",
    "domains/ml-ai/README.md",
    "domains/product-analytics/README.md",
    "domains/recommendation/README.md",
    "domains/risk-compliance/README.md",
    "domains/workforce/README.md",
    "catalog/README.md",
    "catalog/catalog-bundle.md",
    "governance/README.md",
    "governance/access-grants.yaml",
    "governance/scope-guardrails.yaml",
    "templates/README.md",
    "templates/product-onboarding.template.yaml",
    "use-cases/README.md",
    "use-cases/registry.yaml",
    "platform/README.md",
    "platform/ingestion/schema-registry.md",
    "platform/ingestion/source-registry.yaml",
    "platform/ingestion/bronze-landing.md",
    "platform/ingestion/local-bronze-ingestion.md",
    "platform/ingestion/source-offset-hash-idempotency.md",
    "platform/lakehouse/iceberg-table-standards.md",
    "platform/lineage/README.md",
    "platform/orchestration/README.md",
    "platform/orchestration/pipeline-registry.yaml",
    "platform/orchestration/local-recommendation-slice.md",
    "platform/observability/production-slo-release-gates.md",
    "platform/observability/release-evidence-profiles.yaml",
    "platform/quality/README.md",
    "platform/quality/profiles.yaml",
    "platform/serving/semantic-metrics.yaml",
    "platform/processing/README.md",
    "platform/processing/local-medallion-build.md",
    "platform/processing/spark-dbt-standards.md",
    "platform/developer-experience/README.md",
    "platform/developer-experience/product-onboarding-validation.md",
    "platform/environments/local/README.md",
    "platform/environments/local/manifest.yaml",
    "platform/environments/staging/README.md",
    "platform/environments/staging/manifest.yaml",
    "platform/environments/prod/README.md",
    "platform/environments/prod/manifest.yaml",
    "platform/runtime/README.md",
    "platform/runtime/topology.yaml",
    "platform/runtime/iac-modules.yaml",
    "platform/runtime/local/docker-compose.yaml",
    "platform/runtime/iac/README.md",
    "platform/runtime/iac/staging/main.tf",
    "platform/runtime/iac/prod/main.tf",
    "platform/runtime/evidence/README.md",
    "docs/architecture/project-structure-review.md",
    "docs/architecture/enterprise-scope-review.md",
    "docs/enterprise-data-platform-architecture.md",
    "docs/architecture/reference-model-benchmark.md",
    "docs/technology-stack.md",
    "docs/adr/0001-data-platform-project-structure.md",
    "docs/adr/0002-dremio-and-tidb-serving-decision.md",
    "docs/adr/0003-group-enterprise-data-platform-scope.md",
    "docs/team/agent-operating-model.md",
)


def validate_project_structure(root: Path) -> ValidationResult:
    result = ValidationResult()
    for relative in REQUIRED_DIRECTORIES:
        path = root / relative
        if not path.is_dir():
            result.error(path, "required data platform directory is missing")
    for relative in REQUIRED_FILES:
        path = root / relative
        if not path.is_file():
            result.error(path, "required data platform file is missing")
    return result
