package edu.courseflow.loyalty.service;

public final class LoyaltyErrorCodes {

    public static final String LOYALTY_PROGRAM_ALREADY_EXISTS = "LOYALTY_PROGRAM_ALREADY_EXISTS";
    public static final String LOYALTY_PROGRAM_NOT_FOUND = "LOYALTY_PROGRAM_NOT_FOUND";
    public static final String LOYALTY_PROGRAM_INACTIVE = "LOYALTY_PROGRAM_INACTIVE";
    public static final String LOYALTY_INVALID_STATUS = "LOYALTY_INVALID_STATUS";
    public static final String LOYALTY_INVALID_READINESS_QUERY = "LOYALTY_INVALID_READINESS_QUERY";
    public static final String LOYALTY_INVALID_POINTS_DELTA = "LOYALTY_INVALID_POINTS_DELTA";
    public static final String LOYALTY_INVALID_RECONCILIATION_QUERY = "LOYALTY_INVALID_RECONCILIATION_QUERY";
    public static final String LOYALTY_ADJUSTMENT_APPROVAL_REQUIRED = "LOYALTY_ADJUSTMENT_APPROVAL_REQUIRED";
    public static final String LOYALTY_ADJUSTMENT_APPROVAL_NOT_FOUND = "LOYALTY_ADJUSTMENT_APPROVAL_NOT_FOUND";
    public static final String LOYALTY_ADJUSTMENT_APPROVAL_INVALID_STATE = "LOYALTY_ADJUSTMENT_APPROVAL_INVALID_STATE";
    public static final String LOYALTY_ADJUSTMENT_SELF_APPROVAL_DENIED = "LOYALTY_ADJUSTMENT_SELF_APPROVAL_DENIED";
    public static final String LOYALTY_EXPIRY_APPROVAL_REQUIRED = "LOYALTY_EXPIRY_APPROVAL_REQUIRED";
    public static final String LOYALTY_EXPIRY_APPROVAL_MISMATCH = "LOYALTY_EXPIRY_APPROVAL_MISMATCH";
    public static final String LOYALTY_ACCOUNT_NOT_FOUND = "LOYALTY_ACCOUNT_NOT_FOUND";
    public static final String LOYALTY_ACCOUNT_INACTIVE = "LOYALTY_ACCOUNT_INACTIVE";
    public static final String LOYALTY_ENTRY_NOT_FOUND = "LOYALTY_ENTRY_NOT_FOUND";
    public static final String LOYALTY_IDEMPOTENCY_KEY_REUSED = "LOYALTY_IDEMPOTENCY_KEY_REUSED";
    public static final String LOYALTY_IDEMPOTENCY_NOT_REPLAYABLE = "LOYALTY_IDEMPOTENCY_NOT_REPLAYABLE";
    public static final String LOYALTY_SOURCE_REFERENCE_REUSED = "LOYALTY_SOURCE_REFERENCE_REUSED";
    public static final String LOYALTY_INSUFFICIENT_BALANCE = "LOYALTY_INSUFFICIENT_BALANCE";
    public static final String LOYALTY_ENTRY_NOT_REVERSIBLE = "LOYALTY_ENTRY_NOT_REVERSIBLE";
    public static final String LOYALTY_REVERSAL_WOULD_OVERDRAW = "LOYALTY_REVERSAL_WOULD_OVERDRAW";
    public static final String LOYALTY_RESPONSE_NOT_REPLAYABLE = "LOYALTY_RESPONSE_NOT_REPLAYABLE";
    public static final String LOYALTY_ACCESS_DENIED = "LOYALTY_ACCESS_DENIED";
    public static final String LOYALTY_CLIENT_NOT_BOUND = "LOYALTY_CLIENT_NOT_BOUND";
    public static final String LOYALTY_CLIENT_OPERATION_NOT_ALLOWED = "LOYALTY_CLIENT_OPERATION_NOT_ALLOWED";
    public static final String LOYALTY_DEAD_LETTER_NOT_FOUND = "LOYALTY_DEAD_LETTER_NOT_FOUND";
    public static final String LOYALTY_DEAD_LETTER_INVALID_STATE = "LOYALTY_DEAD_LETTER_INVALID_STATE";
    public static final String LOYALTY_INBOUND_EVENT_PAYLOAD_CONFLICT = "LOYALTY_INBOUND_EVENT_PAYLOAD_CONFLICT";
    public static final String LOYALTY_PROMOTION_POINTS_INTENT_INVALID = "LOYALTY_PROMOTION_POINTS_INTENT_INVALID";
    public static final String LOYALTY_REWARD_ALREADY_EXISTS = "LOYALTY_REWARD_ALREADY_EXISTS";
    public static final String LOYALTY_REWARD_NOT_FOUND = "LOYALTY_REWARD_NOT_FOUND";
    public static final String LOYALTY_REWARD_INACTIVE = "LOYALTY_REWARD_INACTIVE";
    public static final String LOYALTY_REWARD_OUT_OF_STOCK = "LOYALTY_REWARD_OUT_OF_STOCK";
    public static final String LOYALTY_REWARD_PROFILE_LIMIT_REACHED = "LOYALTY_REWARD_PROFILE_LIMIT_REACHED";
    public static final String LOYALTY_REWARD_IDEMPOTENCY_KEY_REUSED = "LOYALTY_REWARD_IDEMPOTENCY_KEY_REUSED";
    public static final String LOYALTY_REWARD_INVALID_REQUEST = "LOYALTY_REWARD_INVALID_REQUEST";

    private LoyaltyErrorCodes() {
    }
}
